// FILE: whatsNew/entries.ts
// Purpose: Generated release history for the post-update dialog and settings Release history view.
// Layer: static data consumed by useWhatsNew, WhatsNewDialog, and ChangelogAccordion.
//
// Generated by scripts/release-notes.ts from docs/releases/*.md. Do not edit by hand.

import type { WhatsNewEntry } from "./logic";

export const WHATS_NEW_ENTRIES: readonly WhatsNewEntry[] = [
  {
    version: "0.0.51",
    date: "May 28",
    features: [
      {
        id: "scoop-packaging-is-ready-to-publish",
        title: "Scoop packaging is ready to publish",
        description:
          "Maintainers can now generate a JCode Scoop manifest from a release version and Windows installer SHA256, with clearer Linux, macOS, and Windows install docs in the README.",
      },
      {
        id: "opencode-agents-can-discover-skills",
        title: "OpenCode agents can discover skills",
        description:
          "The server now exposes skill inventory metadata so agents built on OpenCode can list available skills and mention them in conversations.",
      },
      {
        id: "all-themes-now-have-depth-profiles",
        title: "All themes now have depth profiles",
        description:
          "Depth cues (shadows, elevation, layering) are applied consistently across every installed theme, not just the default.",
      },
      {
        id: "navbar-and-sidebar-are-cleaner",
        title: "Navbar and sidebar are cleaner",
        description:
          "The logo stays visible while controls reveal on hover; the project picker uses consistent bordered, elevated styling.",
      },
      {
        id: "chat-transcripts-handle-wide-content-better",
        title: "Chat transcripts handle wide content better",
        description:
          "Markdown tables scroll horizontally inside the pane, diff file paths are copyable, and the keybindings file button moved to the keybindings panel.",
      },
      {
        id: "scoop-installs-stay-under-scoop-management",
        title: "Scoop installs stay under Scoop management",
        description:
          "The generated manifest passes the NSIS installer `/D=$dir` so JCode installs into Scoop's managed app directory.",
      },
      {
        id: "ime-composition-is-preserved",
        title: "IME composition is preserved",
        description:
          "Pressing Enter during IME composition no longer submits the message prematurely; the composition completes first.",
      },
    ],
  },
  {
    version: "0.0.50",
    date: "May 28",
    features: [
      {
        id: "chat-responses-are-easier-to-scan",
        title: "Chat responses are easier to scan",
        description:
          "Catppuccin now has role-based semantic accents for headings, links, inline code roles, and code-block chrome without turning the transcript into a rainbow.",
      },
      {
        id: "the-sidebar-has-clearer-structure",
        title: "The sidebar has clearer structure",
        description:
          "Pinned, Threads, Workspace, and Chats sections now use bold labels with accent icons so the navigation feels less flat.",
      },
      {
        id: "branding-is-more-distinctive",
        title: "Branding is more distinctive",
        description:
          "The navbar wordmark is larger, with a blood-red `J`, and the splash logo now sits in a padded frame that avoids clipping the mark.",
      },
      {
        id: "silent-commands-finish-visibly",
        title: "Silent commands finish visibly",
        description:
          "Commands that complete without stdout now show completion details with duration and exit code instead of looking unfinished.",
      },
      {
        id: "loading-mark-clipping-is-fixed",
        title: "Loading mark clipping is fixed",
        description: "The splash screen logo uses a contained image inside a square-safe frame.",
      },
      {
        id: "completion-output-is-clearer",
        title: "Completion output is clearer",
        description:
          "Successful empty-output commands now display a concrete `Completed ... (exit 0)` style summary.",
      },
    ],
  },
  {
    version: "0.0.49",
    date: "May 25",
    features: [
      {
        id: "keybindings-are-first-class",
        title: "Keybindings are first-class",
        description:
          "Settings now includes a dedicated Keybindings section with search, command groups, source badges, and conflict filters.",
      },
      {
        id: "shortcut-editing-is-safer",
        title: "Shortcut editing is safer",
        description:
          "The recorder blocks unsafe plain letter/number shortcuts and warns before saving over an existing binding.",
      },
      {
        id: "reset-paths-are-built-in",
        title: "Reset paths are built in",
        description:
          "Individual shortcuts and the full keybindings set can be reset back to defaults from the UI.",
      },
      {
        id: "advanced-users-keep-control",
        title: "Advanced users keep control",
        description:
          "The persisted `keybindings.json` remains available as the durable source and advanced escape hatch.",
      },
      {
        id: "release-prep-is-easier-to-repeat",
        title: "Release prep is easier to repeat",
        description:
          "Agent guidance now documents how to prepare future release notes without accidentally publishing early.",
      },
    ],
  },
  {
    version: "0.0.48",
    date: "May 24",
    features: [
      {
        id: "one-concise-changelog-source",
        title: "One concise changelog source",
        description:
          "Per-version Markdown notes now drive both the app release history and GitHub release body.",
      },
      {
        id: "latest-packages-stay-visible",
        title: "Latest packages stay visible",
        description:
          "GitHub Releases keep the newest stable package and the newest prerelease package during testing.",
      },
      {
        id: "old-packages-are-pruned",
        title: "Old packages are pruned",
        description:
          "Older GitHub Release pages and compiled assets are deleted after a newer release publishes.",
      },
      {
        id: "release-checks-fail-loudly",
        title: "Release checks fail loudly",
        description:
          "Missing release notes, stale generated app data, or pruning failures now block the release workflow.",
      },
    ],
  },
  {
    version: "0.0.47",
    date: "May 15",
    features: [
      {
        id: "pi-gets-a-much-sturdier-seat-at-the-table",
        title: "Pi gets a much sturdier seat at the table",
        description:
          "Pi provider sessions now benefit from tighter lifecycle handling, clearer extension-limit warnings, and provider probes that respect the binaries configured in settings.",
      },
      {
        id: "providers-can-keep-themselves-fresher",
        title: "Providers can keep themselves fresher",
        description:
          "Provider auto-update plumbing landed across the app, making it easier to keep agent runtimes current without turning setup and maintenance into a separate chore.",
      },
      {
        id: "create-pr-only-appears-when-it-can-actually-work",
        title: "Create PR only appears when it can actually work",
        description:
          "Create-PR actions now check upstream branch and availability state more carefully, so the UI is quieter until the repository is ready for a real pull request.",
      },
      {
        id: "pending-questions-stop-advancing-at-the-wrong-time",
        title: "Pending questions stop advancing at the wrong time",
        description:
          "Pending user-input auto-advance now cancels on question changes and in-flight responses, reducing stale answers and empty submissions in interrupted provider flows.",
      },
      {
        id: "git-status-and-provider-transcripts-read-cleaner",
        title: "Git status and provider transcripts read cleaner",
        description:
          "Git status refreshes, pull-error messaging, Kilo/OpenCode transcript handling, repo diff scopes, and provider install docs links all picked up focused reliability polish.",
      },
    ],
  },
  {
    version: "0.0.46",
    date: "May 13",
    features: [
      {
        id: "image-attachments-stay-visible-after-sending",
        title: "Image attachments stay visible after sending",
        description:
          "Persisted image previews now load through the same reliable byte-serving path as local generated images, fixing the brief preview flash followed by broken attachment thumbnails.",
      },
      {
        id: "kilo-code-joins-the-provider-lineup",
        title: "Kilo Code joins the provider lineup",
        description:
          "JCode can now launch and monitor Kilo Code sessions alongside Codex, Claude, Cursor, OpenCode, and Gemini, with health checks, settings, mentions, handoff, and model compatibility wired through the app.",
      },
      {
        id: "provider-order-is-now-yours-to-arrange",
        title: "Provider order is now yours to arrange",
        description:
          "The settings screen now lets you drag providers into the order that fits your workflow, and the composer, sidebar, search palette, and plugin surfaces follow the same custom ordering.",
      },
      {
        id: "cleaner-opencode-and-kilo-transcript-updates",
        title: "Cleaner OpenCode and Kilo transcript updates",
        description:
          "Synthetic snapshot progress is filtered more carefully, so restored or refreshed provider output avoids repeating internal progress text while keeping real assistant activity intact.",
      },
      {
        id: "diff-totals-are-easier-to-trust-at-a-glance",
        title: "Diff totals are easier to trust at a glance",
        description:
          "The chat header now owns unified diff totals, keeping added and removed line counts consistent between the header and diff panel as content refreshes.",
      },
    ],
  },
  {
    version: "0.0.45",
    date: "May 12",
    features: [
      {
        id: "opencode-sessions-understand-the-latest-event-stream",
        title: "OpenCode sessions understand the latest event stream",
        description:
          "JCode now tracks the newer OpenCode SDK session events, keeps titles fresher, and has much deeper coverage around OpenCode startup, output, and recovery flows.",
      },
      {
        id: "interrupted-turns-recover-more-predictably",
        title: "Interrupted turns recover more predictably",
        description:
          "Ready and idle transitions now clear or restore turn state more carefully, reducing stuck busy states after reconnects, restarts, and partial provider streams.",
      },
      {
        id: "cursor-model-choices-follow-live-acp-metadata",
        title: "Cursor model choices follow live ACP metadata",
        description:
          "Cursor model selection now normalizes against the provider's current ACP options instead of relying on stale context traits, so the composer better matches what Cursor can actually run.",
      },
      {
        id: "diff-and-pinned-thread-state-stay-in-sync",
        title: "Diff and pinned-thread state stay in sync",
        description:
          "Projection, sidebar, and store updates now carry pinned-thread metadata through the app, while the diff panel handles refreshed content with fewer display glitches.",
      },
      {
        id: "small-workflow-polish-for-git-and-keybindings",
        title: "Small workflow polish for Git and keybindings",
        description:
          "Git summaries are clearer for rename-like moves into untracked folders, and routine keybinding reloads no longer pop a success toast every time they quietly refresh.",
      },
    ],
  },
  {
    version: "0.0.44",
    date: "May 10",
    features: [
      {
        id: "codex-image-generation-now-renders-in-chat",
        title: "Codex image generation now renders in chat",
        description:
          "Generated images from Codex are captured as local artifacts, rendered inline in assistant messages, and include expand and download controls without dragging bulky base64 payloads through the transcript.",
      },
      {
        id: "generated-images-use-a-safer-local-route",
        title: "Generated images use a safer local route",
        description:
          "JCode now serves generated files through a dedicated local-image endpoint with MIME checks, workspace-aware path resolution, and Codex generated_images allowlists for both the normal home and desktop overlay home.",
      },
      {
        id: "provider-favorites-are-quicker-to-manage",
        title: "Provider favorites are quicker to manage",
        description:
          "The provider model picker gained native favorite toggles and cleaner context-menu separators, making large Codex, Cursor, and OpenCode model lists easier to shape around the models you actually use.",
      },
      {
        id: "old-inactive-threads-clean-up-after-seven-days",
        title: "Old inactive threads clean up after seven days",
        description:
          "A safer retention job now removes stale inactive threads in batches, publishes maintenance progress, protects running work and approvals, and compacts SQLite when enough space can be reclaimed.",
      },
      {
        id: "transport-and-server-edges-are-steadier",
        title: "Transport and server edges are steadier",
        description:
          "WebSocket HTTP URL helpers, lifecycle events, provider runtime ingestion, and chat-route plumbing were tightened so generated artifacts and cleanup events move through the app more predictably.",
      },
    ],
  },
  {
    version: "0.0.43",
    date: "May 9",
    features: [
      {
        id: "cursor-is-now-a-first-class-jcode-provider",
        title: "Cursor is now a first-class JCode provider",
        description:
          "Run Cursor CLI sessions directly from JCode with ACP-backed startup, model discovery, existing-chat resume, handoff, and provider health checks alongside Codex and OpenCode.",
      },
      {
        id: "new-effect-ts-acp-runtime",
        title: "New Effect TS ACP runtime",
        description:
          "The new Effect TS ACP package owns generated schemas, JSON-RPC transport, client and agent helpers, terminal release handling, and protocol tests so provider integrations have a sturdier core.",
      },
      {
        id: "the-server-moved-onto-effect-rpc",
        title: "The server moved onto Effect RPC",
        description:
          "WebSocket routing, auth, readiness, settings, environment, git status, and orchestration flows were rebuilt around Effect services so reconnects and failure paths stay more predictable.",
      },
      {
        id: "cursor-output-is-easier-to-read-and-resume",
        title: "Cursor output is easier to read and resume",
        description:
          "Cursor reasoning, tool progress, usage events, plan updates, composer behavior, and model-selection compatibility now render more consistently across fresh and resumed threads.",
      },
      {
        id: "busy-sessions-stay-calmer",
        title: "Busy sessions stay calmer",
        description:
          "Sidebar project recovery, visible-thread PR lookups, task banner resizing, stale target repair, sidechat split handling, and compact chat controls were tightened for heavier day-to-day use.",
      },
    ],
  },
  {
    version: "0.0.41",
    date: "May 2",
    features: [
      {
        id: "sidechat-threads-are-easier-to-track",
        title: "Sidechat threads are easier to track",
        description:
          "Sidechat source metadata now flows through projections, filters, and snapshots so secondary threads stay easier to separate from the main conversation.",
      },
      {
        id: "desktop-startup-feels-faster",
        title: "Desktop startup feels faster",
        description:
          "Packaged desktop builds now open the app window before backend readiness finishes, reducing the blank-start feeling while services come online.",
      },
      {
        id: "git-gained-commit-and-push",
        title: "Git gained commit and push",
        description:
          "The Git actions menu can now commit current work and push it from JCode, keeping the common release and handoff flow closer to the chat.",
      },
      {
        id: "task-controls-are-clearer",
        title: "Task controls are clearer",
        description:
          "Active task controls were tightened, and approval counts are now separated from user input requests so pending work is easier to read at a glance.",
      },
    ],
  },
  {
    version: "0.0.40",
    date: "Apr 29",
    features: [
      {
        id: "browser-use-now-drives-the-visible-browser",
        title: "Browser-use now drives the visible browser",
        description:
          "The desktop browser and browser-use tools now share the same visible webview, so automation, screenshots, navigation, and manual browsing stay in sync instead of racing separate hidden pages.",
      },
      {
        id: "the-browser-panel-is-steadier",
        title: "The browser panel is steadier",
        description:
          "Browser resizing, overlay handling, tab controls, screenshot actions, and browser-use panel requests were tightened while keeping the browser from reopening by default.",
      },
      {
        id: "plans-are-easier-to-export",
        title: "Plans are easier to export",
        description:
          "Proposed plans now share one compact action set for copying markdown, saving into a `.plan` workspace folder, or exporting a markdown file through the desktop save dialog.",
      },
      {
        id: "split-panes-expand-predictably",
        title: "Split panes expand predictably",
        description:
          "Expanding a chat pane now opens that selected chat as the single full-screen surface, closing the rest of the split layout.",
      },
      {
        id: "git-flows-are-smoother",
        title: "Git flows are smoother",
        description:
          "The Git menu now includes branch creation with JCode-style names, and PR creation can recover from GitHub duplicate-PR responses by reusing the existing open pull request.",
      },
      {
        id: "legacy-t3-imports-heal-themselves",
        title: "Legacy T3 imports heal themselves",
        description:
          "A new migration reconciles older imported T3 Code databases whose migration history skipped JCode schema changes, preventing missing-column crashes after import.",
      },
      {
        id: "idle-sessions-clean-up-after-themselves",
        title: "Idle sessions clean up after themselves",
        description:
          "Provider runtimes and Codex discovery sessions now stop after idle periods, while active turns and pending approvals remain protected from premature shutdown.",
      },
      {
        id: "streaming-output-lands-in-the-right-message",
        title: "Streaming output lands in the right message",
        description:
          "Assistant turn ingestion now prefers existing completed item IDs when possible, reducing placeholder duplication and keeping streamed assistant text attached to the intended message.",
      },
      {
        id: "small-workflow-polish-landed",
        title: "Small workflow polish landed",
        description:
          "Diff views can copy the full patch directly, terminal-started chats get a clearer header icon, sidebar titles truncate more cleanly, and long transcripts cap normalized messages for lighter rendering.",
      },
    ],
  },
  {
    version: "0.0.39",
    date: "Apr 28",
    features: [
      {
        id: "split-chats-are-easier-to-arrange",
        title: "Split chats are easier to arrange",
        description:
          "Split chat panes now support direct drag-and-drop, cross-project drops, and safer orphan handling so multi-chat layouts stay easier to build and recover.",
      },
      {
        id: "split-chat-navigation-is-steadier",
        title: "Split chat navigation is steadier",
        description:
          "Split chat activation, route restore, sidebar grouping, and thread subscriptions were tightened so opening and switching chats feels more predictable.",
      },
      {
        id: "opencode-tasks-show-live-progress",
        title: "OpenCode tasks show live progress",
        description:
          "OpenCode todo events now flow into JCode as active task updates, with a compact banner option for keeping current work visible without taking over the chat.",
      },
      {
        id: "opencode-models-can-be-favourited",
        title: "OpenCode models can be favourited",
        description:
          "The model picker now supports OpenCode favourites, making preferred models quicker to find across larger provider model lists.",
      },
      {
        id: "opencode-context-usage-is-tracked",
        title: "OpenCode context usage is tracked",
        description:
          "OpenCode sessions now report context usage more consistently, giving JCode better runtime visibility as conversations grow.",
      },
      {
        id: "debug-controls-stay-out-of-production",
        title: "Debug controls stay out of production",
        description:
          "Debug feature flags are now hidden behind local opt-in behavior, keeping production sidebars cleaner while preserving developer-only controls.",
      },
    ],
  },
  {
    version: "0.0.38",
    date: "Apr 26",
    features: [
      {
        id: "cursor-cli-support-landed",
        title: "Cursor CLI support landed",
        description:
          "Cursor is now available as a provider, with ACP sessions, model discovery, existing chats, handoff, shortcuts, and git text generation wired into JCode.",
      },
      {
        id: "voice-transcription-is-scoped-more-carefully",
        title: "Voice transcription is scoped more carefully",
        description:
          "Voice transcription now stays on ChatGPT sessions, avoiding confusing provider mismatches while keeping dictation available where it is supported.",
      },
      {
        id: "voice-transcription-setup-is-smoother",
        title: "Voice transcription setup is smoother",
        description:
          "Voice transcription setup was tightened so spoken prompts can flow into the composer more reliably in supported ChatGPT sessions.",
      },
      {
        id: "mentions-keep-their-names",
        title: "Mentions keep their names",
        description:
          "Composer replacements now preserve mention labels, so referenced files, apps, and tools remain readable after the prompt text is normalized.",
      },
      {
        id: "plugin-mentions-are-handled-in-prompts",
        title: "Plugin mentions are handled in prompts",
        description:
          "Plugin references can now flow through composer prompts cleanly, making connected-tool context less brittle when you hand work to an agent.",
      },
      {
        id: "toast-behavior-can-be-feature-flagged",
        title: "Toast behavior can be feature-flagged",
        description:
          "Toast notifications picked up feature-flag wiring, giving JCode a safer way to roll notification changes forward or back.",
      },
      {
        id: "desktop-reconnects-are-steadier",
        title: "Desktop reconnects are steadier",
        description:
          "The desktop bridge now refreshes reconnects more reliably and preserves the workspace home directory, reducing drift after desktop runtime restarts.",
      },
    ],
  },
  {
    version: "0.0.37",
    date: "Apr 25",
    features: [
      {
        id: "branch-switching-is-much-safer",
        title: "Branch switching is much safer",
        description:
          "JCode now handles messy branch switches with clearer recovery actions, recreated stashes, unpublished branch publishing, and stronger checks around conflicts and local work.",
      },
      {
        id: "plan-mode-proposals-show-up-properly",
        title: "Plan mode proposals show up properly",
        description:
          "Proposed plans from providers are now parsed and surfaced as first-class UI state, so planning turns feel more predictable instead of blending into ordinary assistant output.",
      },
      {
        id: "desktop-navigation-controls-landed",
        title: "Desktop navigation controls landed",
        description:
          "The desktop app now has app-level back and forward navigation controls, making it easier to move around JCode without losing your place.",
      },
      {
        id: "sidebar-ordering-stays-put",
        title: "Sidebar ordering stays put",
        description:
          "Stored sidebar sort preferences are preserved on load, fixing cases where project and thread ordering could unexpectedly reset.",
      },
      {
        id: "fonts-are-more-consistent",
        title: "Fonts are more consistent",
        description:
          "Theme and chat font handling now share one normalization path, tightening up typography across the chat UI, model controls, and theme settings.",
      },
    ],
  },
  {
    version: "0.0.36",
    date: "Apr 24",
    features: [
      {
        id: "gpt-5-5-is-available",
        title: "GPT-5.5 is available",
        description:
          "GPT-5.5 is now in the model picker with the right default reasoning behavior, so you can move new Codex sessions onto the latest model directly from JCode.",
      },
      {
        id: "opencode-support-is-here",
        title: "OpenCode support is here",
        description:
          "OpenCode is now available as a provider, with runtime model discovery, session handling, provider settings, model search, variants, agents, and git text generation wired into the app.",
      },
      {
        id: "model-search-feels-faster",
        title: "Model search feels faster",
        description:
          "Large OpenCode model lists now get provider-aware search, clearer labels, automatic search focus, arrow-key navigation, and tighter picker clipping.",
      },
      {
        id: "diffs-now-start-from-the-turn",
        title: "Diffs now start from the turn",
        description:
          "Turn diffs use turn-start checkpoints, making changed-file views line up more closely with what the agent actually changed in the current turn.",
      },
      {
        id: "chat-markdown-is-smarter",
        title: "Chat markdown is smarter",
        description:
          "Math rendering was added to chat markdown, while literal dollar amounts stay intact so normal prices and currency snippets do not get misread as formulas.",
      },
      {
        id: "more-polish-around-search-and-releases",
        title: "More polish around search and releases",
        description:
          "Sidebar theme search, release verification, Windows signing config, and a handful of provider/model edge cases were tightened up for a smoother build and update path.",
      },
    ],
  },
  {
    version: "0.0.35",
    date: "Apr 22",
    features: [
      {
        id: "project-import-browsing-got-smarter",
        title: "🗂️ Project import browsing got smarter",
        description:
          "The import palette can now browse nearby paths more directly, helping you find and open the right project location with less guesswork.",
      },
      {
        id: "provider-usage-is-visible-in-context",
        title: "📊 Provider usage is visible in-context",
        description:
          "The branch toolbar now surfaces provider usage snapshots, making it easier to keep an eye on current usage without leaving your working view.",
      },
      {
        id: "desktop-startup-feels-clearer",
        title: "🚀 Desktop startup feels clearer",
        description:
          "JCode now shows a proper splash screen while the desktop backend spins up, so launch feels intentional instead of looking briefly stalled.",
      },
      {
        id: "better-provider-and-theme-polish",
        title: "🎛️ Better provider and theme polish",
        description:
          "Model capability handling, theme editing, and related picker behavior were tightened up so settings feel more consistent and trustworthy.",
      },
      {
        id: "desktop-release-plumbing-is-sturdier",
        title: "🛠️ Desktop release plumbing is sturdier",
        description:
          "Startup readiness checks, desktop packaging config, and platform entitlements were refined to make desktop builds and app boot more reliable.",
      },
    ],
  },
  {
    version: "0.0.34",
    date: "Apr 21",
    features: [
      {
        id: "theme-packs-are-editable",
        title: "🎨 Theme packs are editable",
        description:
          "The new theme pack editor lets you tune UI colors directly in JCode, with shared theme tokens keeping the sidebar, composer, transcript, and controls in sync.",
      },
      {
        id: "sidebar-notifications-are-easier-to-read",
        title: "🔔 Sidebar notifications are easier to read",
        description:
          "Thread activity now surfaces more clearly in the sidebar, so updates, background work, and attention states are easier to spot without opening every conversation.",
      },
      {
        id: "steadier-transcripts-under-load",
        title: "🧵 Steadier transcripts under load",
        description:
          "Transcript rendering and sidebar-owned state were separated more cleanly, reducing unnecessary churn while long conversations and live agent output are moving.",
      },
      {
        id: "safer-runtime-mode-recovery",
        title: "🛡️ Safer runtime-mode recovery",
        description:
          "Codex runtime permissions now propagate more reliably across resumed sessions and provider restarts, keeping the app closer to the mode you actually selected.",
      },
      {
        id: "cleaner-composer-and-picker-styling",
        title: "✨ Cleaner composer and picker styling",
        description:
          "Composer chrome, picker hover states, runtime controls, and changed-file rows picked up a more consistent visual pass across light and dark themes.",
      },
    ],
  },
  {
    version: "0.0.33",
    date: "Apr 20",
    features: [
      {
        id: "browse-local-folders-right-from-the-composer",
        title: "📂 Browse local folders right from the composer",
        description:
          "Folder mentions now open a real local directory picker, so you can drill into nearby files and attach the right path without leaving the chat flow.",
      },
      {
        id: "cleaner-file-and-folder-mentions",
        title: "🗂️ Cleaner file and folder mentions",
        description:
          "Mention chips, file trees, and changed-file rows now use a lighter shared icon system that keeps paths easier to scan across the app.",
      },
      {
        id: "stronger-desktop-browser-runtime",
        title: "🌐 Stronger desktop browser runtime",
        description:
          "The desktop browser path picked up better IPC plumbing, screenshots, clipboard support, and more efficient state syncing for browser-driven tasks.",
      },
      {
        id: "smoother-startup-and-provider-recovery",
        title: "🛟 Smoother startup and provider recovery",
        description:
          "Project hydration, desktop startup, auth visibility, and aborted-turn cleanup were tightened up so sessions recover more predictably after interruptions.",
      },
    ],
  },
  {
    version: "0.0.32",
    date: "Apr 19",
    features: [
      {
        id: "steering-messages-are-clearly-marked",
        title: "↪︎ Steering messages are clearly marked",
        description:
          "Messages sent with steering now keep a lightweight 'Steering conversation' label above the bubble, even after the app reconciles with the server.",
      },
      {
        id: "less-aggressive-background-return-checks",
        title: "🚦 Less aggressive background return checks",
        description:
          "Desktop update checks now wait for a real background return instead of reacting to every tiny blur/focus bounce.",
      },
      {
        id: "no-more-stuck-checking-state",
        title: "🛟 No more stuck checking state",
        description:
          "If the updater never answers, JCode now times out and recovers instead of hanging on a permanent Checking status.",
      },
    ],
  },
  {
    version: "0.0.31",
    date: "Apr 19",
    features: [
      {
        id: "gemini-support-is-here",
        title: "♊ Gemini support is here",
        description:
          "Use Gemini alongside Codex and Claude Agent, with provider-aware models and handoff support built into the app.",
      },
      {
        id: "custom-binary-paths-for-every-provider",
        title: "🛠️ Custom binary paths for every provider",
        description:
          "Point JCode at your own Codex, Claude, or Gemini binary when your setup lives outside the default install path.",
      },
      {
        id: "reuse-assistant-replies-as-attachments",
        title: "📎 Reuse assistant replies as attachments",
        description:
          "Select parts of an assistant response and send them back as structured context in your next prompt.",
      },
      {
        id: "better-thread-continuity",
        title: "🧵 Better thread continuity",
        description:
          "The app now remembers your last open thread, carries pull request context into draft threads, and keeps sidebar state more stable.",
      },
      {
        id: "smoother-recovery-and-update-checks",
        title: "🩹 Smoother recovery and update checks",
        description:
          "Project creation recovery, foreground update checks, and a few rough edges around long messages and download state have been tightened up.",
      },
    ],
  },
  {
    version: "0.0.30",
    date: "Apr 18",
    features: [
      {
        id: "chats-are-now-available",
        title: "💬 Chats are now available!",
        description: "Write without a selected project, or create threads from there.",
      },
      {
        id: "new-shortcuts",
        title: "⌨️ New shortcuts",
        description:
          "Quickly open a new chat or jump to your latest project thread with dedicated shortcuts.",
      },
      {
        id: "claude-1m-context-support",
        title: "🧠 Claude 1M context support",
        description:
          "Take full advantage of Claude's 1M-token context window for long conversations and large codebases.",
      },
      {
        id: "bulk-thread-actions",
        title: "📁 Bulk thread actions",
        description: "Select multiple threads at once and act on them together.",
      },
      {
        id: "cleaner-reasoning-picker-order",
        title: "✨ Cleaner reasoning picker order",
        description:
          "The reasoning picker has been reordered to make the most common choices quicker to reach.",
      },
      {
        id: "new-polished-ui-ux",
        title: "💻 New polished UI/UX",
        description: "A round of visual and interaction polish across the app.",
      },
    ],
  },
  {
    version: "0.0.29",
    date: "Apr 18",
    features: [
      {
        id: "what-s-new-inline",
        title: "🆕 What's new, inline",
        description:
          "Every update now opens a one-time dialog highlighting the latest changes, so you don't have to hunt through a changelog to know what shipped.",
      },
      {
        id: "release-history-in-settings",
        title: "📚 Release history in Settings",
        description:
          "A full changelog lives under Settings → Release history, grouped by version in a collapsible accordion.",
      },
      {
        id: "release-history-stays-easy-to-revisit",
        title: "Release history stays easy to revisit",
        description:
          "This release remains available in the generated in-app history after GitHub package pages are pruned.",
      },
    ],
  },
];
